### ISSUE TITLE
Delays in Pilots requesting oceanic clearance

### ISSUE THREAD

**Issue by Paulmc98** [vatsimnetwork/nattrak#101]
I had a pilot notify me that the website would not let them request oceanic clearance as they were further than 45 minutes away from the entry point. 

Can the system allow requests up to 1 hour before their entry point?

**Comment by lieselwd** [comment]
Changed in https://github.com/vatsimnetwork/nattrak/pull/107/commits/1868912ab970a1316299921d7fb9ebabda51b3aa
