### ISSUE TITLE
April 2024 RCL changes

### ISSUE THREAD

**Issue by gthomasuk** [vatsimnetwork/nattrak#125]
Changes required as part of new RCL process to come into effect 09-Apr-2024. 

- Automatic message stating ‘ RCL RECEIVED. FLY CURRENT FLIGHT PLAN ROUTE OR AMMEND OR AMENDED BY ATC ‘ if submitted within current allowed times

- Submission of oceanic flight plan 
If able by entry point, RCL to be accepted on Nattrack on Gander between 90 - 30 Mins (90-60 real world but due to controller visibility restrictions local agreement to extend to 30 mins before entry)  
Shanwick 60 - 30 Mins
Santa Maria 40 Mins or more 
BIRD 20 mins or more 
New York - Unchanged
If this one change for all then please set to between 15 to 90 mins before entry. 

- If submitted outside of time ranges then message RCL REJECT - CONTACT ON VOICE to sent to pilot

- Nattrack to flash processed flight plan if any conflict identified

**Comment by lieselwd** [comment]
I've received no indication from CTP team that these changes are to be implemented for the event however it may be possible to have it enabled outside of CTP. Have these changes been reflected on a new Gander/Shanwick SOP document?

> If submitted outside of time ranges then message RCL REJECT - CONTACT ON VOICE to sent to pilot

This is already implemented but as a validation error on the RCL. I'd rather not create an RCL in the database if it's just going to be auto rejected. Is there an advantage to doing it this way?

> Nattrack to flash processed flight plan if any conflict identified

Please provide more detail

**Comment by gthomasuk** [comment]
Hello. Talks are undergoing at present between the Directors and Operations of all OCAs and domestic surrounding FIRs. I should have a clear update for you within the next few days.

**Comment by gthomasuk** [comment]
@lieselwd This has now been agreed by all parties and documents are in draft state. 

One little amendment required to the wording to the Auto reply message
” RCL RECEIVED. FLY CURRENT FLIGHT PLAN OR AS AMENDED BY ATC. CONTINUE TO MONITOR NATTRAK UNTIL ENTERING OCA “ This is to ensure any amendments made by OCA controller are actioned before reaching the OEP

**Comment by lieselwd** [comment]
Changed #126
