### ISSUE TITLE
A route that I don't think I would normally have access to? (NOTAMS)

### ISSUE THREAD

**Issue by Jules010209** [vatsimnetwork/nattrak#133]
I did a google search, and found this URL on Google's indexer: https://nattrak.vatsim.net/notams/create. I didn't think it would work, but when I pressed the ‘Create’ button, it was added to your notams list. I'm sorry if this is normal but I just want to warn you, in case the wrong person finds it.

**Comment by lieselwd** [comment]
Well that’s awkward lol

will fix this, thank you very much :)

**Comment by lieselwd** [comment]
Fixed with 5f0f25f261d29299003e8f5faf36df1dd39e573d
