### ISSUE TITLE
Revised language for "RCL RECEIVED" message

### ISSUE THREAD

**Issue by mythicfci** [vatsimnetwork/nattrak#135]
Hi, I'm VATSIM Scandinavia's Events Assistant for Iceland and the facility engineer for BIRD FIR/OCA. I recently became aware of the fact that the new "RCL RECEIVED" message is being changed slightly by mutual agreement of the OCAs. See the following screenshot from BIRD AIP SUP 10/2024:

![IMG_9434](https://github.com/vatsimnetwork/nattrak/assets/49729038/8535654f-b4fb-478b-8603-fa9f13023bd0)

I have discussed this matter with other VATSIM OCA staff (Gary from Gander/Shanwick and Bernardo from Santa Maria; NY is not affected), and we have agreed that we would like the RCL RECEIVED language **on Nattrak** amended as following:
_Instead of:_
> RCL RECEIVED. FLY CURRENT FLIGHT PLAN OR AS AMENDED BY ATC. CONTINUE TO MONITOR NATTRACK PAGE UNTIL ENTERING OCA

**_Nattrak's "RCL received" message (when implemented) should read:_**
> **RCL RECEIVED. CONTINUE TO MONITOR NATTRAK UNTIL ENTERING OCA**

Thanks very much in advance for your assistance on this!

**Comment by lieselwd** [comment]
This can be changed

FIY these changes have been pushed back and are currently not live on natTrak (https://github.com/vatsimnetwork/nattrak/pull/129). I'm still waiting on having a proper specification to look at for what the changes should be, as discussed in the vatsim tech discord.

**Comment by pinatacolada** [comment]
Since late June this message has been further updated to: `RCL RECEIVED BY LPPO SANTA MARIA RADIO HF 13354 OR 11309`

The frequencies is an add on to the standard "RCL RECEIVED BY XXXX". 
https://ops.group/blog/wp-content/uploads/2024/06/NAT-OPS-Bulletin-2023_001-Rev04.pdf
