### ISSUE TITLE
Ocean Planned Altitudes link to ES

### ISSUE THREAD

**Issue by Jagardstrong** [vatsimnetwork/nattrak#138]
Is it possible to somehow link the cleared altitude in an oceanic clearance to Euroscope? 

For example, a QM/QX domestic controller only knows the ocean cleared level by viewing the Nattrak site. It would be a big QoL improvement if this could be linked via a plugin and displayed under one of our lists. 

The same would apply to a clearance issued or pending indication? 

Jagard

**Comment by lieselwd** [comment]
Hey Jagard, very sorry for forgetting about replying until now.

Plugins that do this already exist (VATUK UKCPlugin, Vateir plugin, etc). Use the endpoint https://nattrak.vatsim.net/api/clx-messages.
