### ISSUE TITLE
Oceanic ATC unable to access website one connected.

### ISSUE THREAD

**Issue by gthomasuk** [vatsimnetwork/nattrak#140]
Server 500 error being displayed

**Comment by lieselwd** [comment]
I'm unable to recreate this by attempting to clear an aircraft. Could you please provide detail? E.g. URL where error 500 occurs, time/date, etc

**Comment by lieselwd** [comment]
Nevermind I found the issue... it didn't reveal itself to me because of administrator permissions. Fixed in new 1.7.2 https://github.com/vatsimnetwork/nattrak/pull/141
