### ISSUE TITLE
Include Bodø OFIR (ENOB) into nattrak

### ISSUE THREAD

**Issue by Adrian2k** [vatsimnetwork/nattrak#165]
Hello.

Tried sending a mail 2 weeks about this, but as I havent recieved any response yet I will also create this issue.
We are looking into including ENOB into the nattrak solution - ENOB is already apart of the NAT region.

Our (only oceanic) neighbour Reykjavik is already apart of nattrak,

-Adrian Bjerke

I can also be reached on the following:
adrian.bjerke@vatsim-scandinavia.org
Discord: Adrian2k

**Comment by lieselwd** [comment]
Hi Adrian, 

Sorry- thats on me for forgetting to readd the vatsim email to my email client!

I'll add them in. Can I please just confirm the prefix used to login to the VATSIM network? (i.e. EGTT is LON_)

**Comment by Adrian2k** [comment]
ENOB_CTR is our only logon

**Comment by morettio** [comment]
Any more news here?

**Comment by lieselwd** [comment]
Hi, this should be added now :) Apologies for the delay; I've been waiting on some updates to be pushed. Let me know if you you encounter any issues or if anything else needs doing.
