### ISSUE TITLE
Idiot-proof indication of clearance approvals

### ISSUE THREAD

**Issue by erikquinn** [vatsimnetwork/nattrak#27]
During CTP, controllers had reported multiple cases of pilots asking on frequency about how they would know when their clearance was approved on nattrak. So I guess the way the approval is indicated to the pilots could perhaps be made more obvious. Something as simple as a big `STATUS: ON REQUEST` --> `STATUS: APPROVED` / `STATUS: APPROVED WITH LEVEL CHANGE` / `APPROVED WITH RTE CHANGE` / etc.

Something super obvious would help to alleviate the questions. About 90-95% of pilots had no issue, but there's always a few 😄

**Comment by liessdow** [comment]
Looking at the code for the pilot message history, it needs a re-write. Will defer this to that.
