### ISSUE TITLE
Remove requests from Pending Messages list once clearance is sent, without refreshing

### ISSUE THREAD

**Issue by erikquinn** [vatsimnetwork/nattrak#29]
Obviously overhead is always a concern. But we should consider the practicality of having the Pending RCL Messages list update to remove requests from that list, _without refreshing_, when the clearances are processed and sent.

The current workflow for the controllers is to open up the clearance requests in new tabs, compare against a second screen with the processed clearances, then for each clearance request, send the approval and close the tabs. After addressing the tabs opened, they will refresh the Pending RCL Messages list to clear out the clearances that have already been addressed. And that refresh will obviously contribute to server load as the constant refreshing will be frequently querying the server for _all_ the active clearances.

**Comment by liessdow** [comment]
Done because of https://github.com/vatsimnetwork/nattrak/commit/5ef4c2c30af9fb4cc066b4ed92fe0c3fbd914ce2
